UPDATE product_catalog SET cost_price = 100 WHERE name = 'Abraçadeira pacote com 100';
UPDATE product_catalog SET cost_price = 160 WHERE name = 'Abrigo para extintor externo sobrepor';
UPDATE product_catalog SET cost_price = 255 WHERE name = 'Abrigo, caixa para Mangueira 90x60x17 sobrepor';
UPDATE product_catalog SET cost_price = 63.89 WHERE name = 'ACIONADOR MANUAL ENDER. SEM SIRENE COMPACT SEGURIMAX';
UPDATE product_catalog SET cost_price = 33 WHERE name = 'ACIONADOR MANUAL C/ SIRENE CONVENCIONAL segurirmax';
UPDATE product_catalog SET cost_price = 103.29 WHERE name = 'ACIONADOR MANUAL ENDEREÇAVEL COM SIRENE COMPACT SEGURIMAX';
UPDATE product_catalog SET cost_price = 68.32 WHERE name = 'ACIONADOR MANUAL ENDERECAVEL S/ SIRENE AME 521, Intelbrás';
UPDATE product_catalog SET cost_price = 5.16 WHERE name = 'CHAVE STORZ P/CONEXOES 1.1/2X2.1/2 ALUM';
UPDATE product_catalog SET cost_price = 18.82 WHERE name = 'ADAPTADOR PRA ESGUICHO 1.1/2X2.1/2" ALUMINIO';
UPDATE product_catalog SET cost_price = 257 WHERE name = 'Adesivo Epoxi profissional, cola 1,8kg';
UPDATE product_catalog SET cost_price = 580.5 WHERE name = 'ARALDITE,ADESIVO EPOXI 1,8KG PROFISSIONAL';
UPDATE product_catalog SET cost_price = 320 WHERE name = 'Balão de AR/ TANQUE DE PRESSAO 12L';
UPDATE product_catalog SET cost_price = 15.31 WHERE name = 'BARRAMENTO TERRA 08 FUROS C/SUP VD';
UPDATE product_catalog SET cost_price = 86.23 WHERE name = 'TUBO PVC SOLDAVEL 50MM';
UPDATE product_catalog SET cost_price = 47.83 WHERE name = 'BASE MASTRO 2" POLEGADAS, ACO ELETRO';
UPDATE product_catalog SET cost_price = 110 WHERE name = 'BATERIA 12V 7ah';
UPDATE product_catalog SET cost_price = 620 WHERE name = 'Bateria 150 Amperes cral a base de troca, garantia de 15 meses sem manutenção';
UPDATE product_catalog SET cost_price = 51 WHERE name = 'Bateria selada 12v 1.3 Amper';
UPDATE product_catalog SET cost_price = 270 WHERE name = 'Bateria selada 12 V 18 AH';
UPDATE product_catalog SET cost_price = 20.85 WHERE name = 'BICO DE SPRINKLER PENDENTE 1/2" 68 K-80 CR 15MM SPK';
UPDATE product_catalog SET cost_price = 27.57 WHERE name = 'BOIA AUTOMATICO DE NIVEL 1,2MT, SOORANO';
UPDATE product_catalog SET cost_price = 5714.8 WHERE name = 'BOMBA CENTRIFUGA TRIFASICA PRA INCENDIO ,5CV 2.1/2X2.1/2" BPI21R';
UPDATE product_catalog SET cost_price = 2.75 WHERE name = 'Bucha redução galvanizado 1/2" x 1/4"';
UPDATE product_catalog SET cost_price = 44.29 WHERE name = 'Bucha 2.1/2 x 1" de redução  galvanizado';
UPDATE product_catalog SET cost_price = 40.91 WHERE name = 'Bucha 3"x 2 .1/2 Redução  galvanizado SEGURIMAX';
UPDATE product_catalog SET cost_price = 16.92 WHERE name = 'Bucha de redução 2"x1" Galvanizado';
UPDATE product_catalog SET cost_price = 19.87 WHERE name = 'Bucha de redução  Galvanizado 2.1/2×1"';
UPDATE product_catalog SET cost_price = 127.95 WHERE name = 'Cabo 1,5 mm flexível vermelho 750v';
UPDATE product_catalog SET cost_price = 195.07 WHERE name = 'Cabo flexível 2,5 mm vermelho 750V';
UPDATE product_catalog SET cost_price = 605.78 WHERE name = 'Cabo 4p p/ CFTV, CABO REDE LAN 4P CAT5E AZUL CMX 305M MEGATRON';
UPDATE product_catalog SET cost_price = 3.6 WHERE name = 'Cabo blindado p/ incêndio 2 x 1,5mm';
UPDATE product_catalog SET cost_price = 5.43 WHERE name = 'CABO DE INCENDIO 2X1.50MM NBR 17240 VERMELHO';
UPDATE product_catalog SET cost_price = 498.9 WHERE name = 'CABO FLEXIVEL 6,0MM 750V';
UPDATE product_catalog SET cost_price = 154.5 WHERE name = 'CABO COAXIAL CFTV BIP 80% 4MM BR 100M';
UPDATE product_catalog SET cost_price = 11.46 WHERE name = 'CAIXA DE INSPECAO PRA ,ATERRAMENTO, 20X23CM PVC';
UPDATE product_catalog SET cost_price = 4.16 WHERE name = 'CAIXA CONDULETE PVC  4X2 05 ENTRADA';
UPDATE product_catalog SET cost_price = 419.2 WHERE name = 'CAIXA DE MEDICAO METAL TRIFASICO, CEB P1';
UPDATE product_catalog SET cost_price = 7.07 WHERE name = 'Caixa CONDULETE MULTIPLO 3/4" X S/T';
UPDATE product_catalog SET cost_price = 2.36 WHERE name = 'CANOPLA PRA /SPRINKLER 1/2" ALUMINIO';
UPDATE product_catalog SET cost_price = 106.5 WHERE name = 'CAPTOR FRANKLIN COM 2 DECIDAS 300MM LATAO 3/4';
UPDATE product_catalog SET cost_price = 485.85 WHERE name = 'CENTRAL INCENDIO 12 LACOS 12V CONVENCIONAL SEGURIMAX';
UPDATE product_catalog SET cost_price = 1447.69 WHERE name = 'CENTRAL DE INCENDIO 125 LACOS 24V ENDEREÇAVEL SEGURIMAX';
UPDATE product_catalog SET cost_price = 596.86 WHERE name = 'CENTRAL DE INCENDIO 12 LACOS 24V CONVENCIONAL SEGURIMAX';
UPDATE product_catalog SET cost_price = 1250 WHERE name = 'Central de alarme de incêndio Verin VR 40. com display digital sem baterias.';
UPDATE product_catalog SET cost_price = 443.64 WHERE name = 'CENTRAL INCENDIO 24 LACOS 12V CONVENCIONAL SEGURIMAX';
UPDATE product_catalog SET cost_price = 445 WHERE name = 'Central de alarme digital verin VR-08 com display digital sem baterias.';
UPDATE product_catalog SET cost_price = 6 WHERE name = 'Chave storz dupla';
UPDATE product_catalog SET cost_price = 8.26 WHERE name = 'ADESIVO PVC 175GR COM /PINCEL';
UPDATE product_catalog SET cost_price = 5.9 WHERE name = 'Conector botinha 35 mm Tipo terminal de pressão.';
UPDATE product_catalog SET cost_price = 9.15 WHERE name = 'Conector botinha 50mm/Terminal de pressão.';
UPDATE product_catalog SET cost_price = 4.54 WHERE name = 'CONECTOR BOTINHA ,TERMINAL DE PRESSAO 16MM';
UPDATE product_catalog SET cost_price = 2.53 WHERE name = 'Conector U CLIPS PRA,REBAR GALVANIZADO 3/8" 8-10MM';
UPDATE product_catalog SET cost_price = 2.65 WHERE name = 'CONECTOR P/HASTE DE ATERRAM 3/4"';
UPDATE product_catalog SET cost_price = 11.39 WHERE name = 'CONECTOR SPLIT BOLD 35MM';
UPDATE product_catalog SET cost_price = 15.55 WHERE name = 'CONECTOR SPLIT BOLD 50MM';
UPDATE product_catalog SET cost_price = 2.6 WHERE name = 'Conector tipo Clipes, CLIPS P/REBAR GALV 3/8" 8-10MM  termotecnica';
UPDATE product_catalog SET cost_price = 270.45 WHERE name = 'COPEX METAL FLEX REV 3/4" 30MT';
UPDATE product_catalog SET cost_price = 289.34 WHERE name = 'CORDAO PARALELO TORCIDO 2X1,5MM BR';
UPDATE product_catalog SET cost_price = 17.8 WHERE name = 'CORDOALHA 35MM COBREADA NORMATIZADA';
UPDATE product_catalog SET cost_price = 39.27 WHERE name = 'CORDOALHA 50MM COBRE NU';
UPDATE product_catalog SET cost_price = 21.32 WHERE name = 'Cotovelo 1 1/2" galvanizado 90º';
UPDATE product_catalog SET cost_price = 17.83 WHERE name = 'cotovelo  1 1/4" Galvanizado 45º';
UPDATE product_catalog SET cost_price = 10.97 WHERE name = 'Cotovelo galvanizado 45 1"';
UPDATE product_catalog SET cost_price = 7.29 WHERE name = 'Cotovelo galvanizado 90º 1"';
UPDATE product_catalog SET cost_price = 35.25 WHERE name = 'Cotovelo galvanizado 90º 2.1/2"';
UPDATE product_catalog SET cost_price = 33.51 WHERE name = 'cotovelo 2" polegadas Galvanizado 45º';
UPDATE product_catalog SET cost_price = 30.85 WHERE name = 'Cotovelo 2" galvanizado 90º';
UPDATE product_catalog SET cost_price = 7.16 WHERE name = 'COTOVELO GALVANIZADO 90, 3/4"';
UPDATE product_catalog SET cost_price = 176.86 WHERE name = 'COTOVELO GALVANIZADO 45, 4"';
UPDATE product_catalog SET cost_price = 11.61 WHERE name = 'Cotovelo reduzido 1 x 1/2" galvanizado 90º';
UPDATE product_catalog SET cost_price = 71.29 WHERE name = 'CURVA GALVANIZADA F 2" ,90';
UPDATE product_catalog SET cost_price = 1.94 WHERE name = 'Curva galvanizado Eletrolítica 90°×03/4"';
UPDATE product_catalog SET cost_price = 161.83 WHERE name = 'Detector de temperatura endereçável';
UPDATE product_catalog SET cost_price = 85.03 WHERE name = 'DETECTOR DE TEMPERATURA CONVEBCIONAL';
UPDATE product_catalog SET cost_price = 35.26 WHERE name = 'DPS UNIPOLAR 45KA CLASSE II';
UPDATE product_catalog SET cost_price = 2940.92 WHERE name = 'BOMBA CENT TRIFAZICA 3CV 2.1/2X2.1/2"BPI92SR';
UPDATE product_catalog SET cost_price = 66.49 WHERE name = 'ELETRODUTO PVC CORRUG 25MMX50MT AM';
UPDATE product_catalog SET cost_price = 12.71 WHERE name = 'ELETRODUTO PVC RIGIDO ROSC 3MT 3/4"';
UPDATE product_catalog SET cost_price = 83.69 WHERE name = 'ESGUICHO 1.1/2" JATO REGULAVEL 3 POSIÇOES ALUMINIO';
UPDATE product_catalog SET cost_price = 17.7 WHERE name = 'Esguicho de jato Sólido alum';
UPDATE product_catalog SET cost_price = 2.09 WHERE name = 'ESTICADOR PRA CABO DE ACO 1/4-6MM';
UPDATE product_catalog SET cost_price = 4.21 WHERE name = 'ESTICADOR PRA CABO DE ACO 3/8-10MM';
UPDATE product_catalog SET cost_price = 77.84 WHERE name = 'ESTICADOR PRA CABO DE ACO 7/8-22MM';
UPDATE product_catalog SET cost_price = 15.48 WHERE name = 'Fita ante-corrosiva. p gás FITA SILVERTAPE 25MTX48MM';
UPDATE product_catalog SET cost_price = 24.64 WHERE name = 'FITA DEMARCACAO SOLO 50MMX30MT AMARELO';
UPDATE product_catalog SET cost_price = 5.86 WHERE name = 'FITA ISOLANTE 18MMX20METRO';
UPDATE product_catalog SET cost_price = 28.76 WHERE name = 'Fita perfurada caixa, 17X0,40X30 GALVANIZADO';
UPDATE product_catalog SET cost_price = 1.25 WHERE name = 'FITA VEDA ROSCA 12MMX 25 METRO';
UPDATE product_catalog SET cost_price = 112.05 WHERE name = 'FLANGE GALVANIZADO SEXTAVADA 3" POLEGADAS';
UPDATE product_catalog SET cost_price = 16.86 WHERE name = 'ADAPTADO AA FLANGE+ANEL CAIXA  DAGUA 50MM 1.1/2';
UPDATE product_catalog SET cost_price = 11.28 WHERE name = 'AGUA RAZ 900ML';
UPDATE product_catalog SET cost_price = 64.93 WHERE name = 'TINTA ESMALTE BRIL STD 3,0LT HIPER AMARELO';
UPDATE product_catalog SET cost_price = 68.87 WHERE name = 'TINTA ESMALTE BRIL STD 3,0LT DELANIL PRETO';
UPDATE product_catalog SET cost_price = 21.03 WHERE name = 'HASTE PRA ATERRAMENTO 3/8" 3,00 METROS';
UPDATE product_catalog SET cost_price = 15.46 WHERE name = 'RODANA ISOLADOR SIMP 2 DECIDA MASTRO 1.1/2"ACO ELET';
UPDATE product_catalog SET cost_price = 3.34 WHERE name = 'JOELHO PVC SOLDAVEL 90 50MM';
UPDATE product_catalog SET cost_price = 166.95 WHERE name = 'UNIAO GALVANIZADO C/ASSENTO BRONZE 2.1/2"';
UPDATE product_catalog SET cost_price = 27.07 WHERE name = 'LIXA MASSA/MAD G120 50FOLHAS A257';
UPDATE product_catalog SET cost_price = 15.76 WHERE name = 'LUMIN EMERGENCIA 30 LEDS';
UPDATE product_catalog SET cost_price = 8.44 WHERE name = 'Luva  1" galvanizado';
UPDATE product_catalog SET cost_price = 21.88 WHERE name = 'Luva galvanizado 2"';
UPDATE product_catalog SET cost_price = 4.87 WHERE name = 'Luva  3/4" galvanizado';
UPDATE product_catalog SET cost_price = 8.21 WHERE name = 'Luva galvanizado redução 1x1/2"';
UPDATE product_catalog SET cost_price = 299.9 WHERE name = 'Mangueira de incêndio tipo I MANG INCENDIO TIPO I 1.1/2 15M';
UPDATE product_catalog SET cost_price = 313.48 WHERE name = 'Mangueira de incêndio tipo II MANG INCENDIO TIPO II 1.1/2 15M';
UPDATE product_catalog SET cost_price = 8.3 WHERE name = 'MAO FRANCESA 20CM PRATA';
UPDATE product_catalog SET cost_price = 6.97 WHERE name = 'MAO FRANCESA 15CM PRATA';
UPDATE product_catalog SET cost_price = 29 WHERE name = 'Martelinho para acionador manual do tipo quedra vidro';
UPDATE product_catalog SET cost_price = 196.63 WHERE name = 'Mastro 3 metros aço galvanizado com redução 1.1/2"';
UPDATE product_catalog SET cost_price = 110.69 WHERE name = 'MODULO ISOLADOR DE LACO ENDERECAVEL SEGURIMAX';
UPDATE product_catalog SET cost_price = 86.26 WHERE name = 'MODULO ISOLADOR DE LACO COMPACT SEGURIMAX';
UPDATE product_catalog SET cost_price = 137.81 WHERE name = 'MODULO SAIDA ENDERECAVEL SEGURIMAX';
UPDATE product_catalog SET cost_price = 108.55 WHERE name = 'MODULO SAIDA COMPACT SEGURIMAX';
UPDATE product_catalog SET cost_price = 5.98 WHERE name = 'Niple 1/4" galvanizado';
UPDATE product_catalog SET cost_price = 5.21 WHERE name = 'Niple galvanizado 1"';
UPDATE product_catalog SET cost_price = 5.18 WHERE name = 'NIPLE DUPLO GALVANIZADO 3/4"';
UPDATE product_catalog SET cost_price = 93.51 WHERE name = 'Niple duplo de  4"polegadas galvanizado.';
UPDATE product_catalog SET cost_price = 13.99 WHERE name = 'PARAF AA CHIP MDF CH PH 4,5X45 200UN BC';
UPDATE product_catalog SET cost_price = 1.47 WHERE name = 'Parabolt chumbador, 3/8X3"';
UPDATE product_catalog SET cost_price = 38.26 WHERE name = 'PARAF PB TROM PHP GESSO 3,5X25 1000UN FO';
UPDATE product_catalog SET cost_price = 1.05 WHERE name = 'Presilha tipo chapinha em U PRESILHA TIPO U P/CABO 16/50MM2';
UPDATE product_catalog SET cost_price = 213.53 WHERE name = 'QUADRO COMANDO 400X300X200 S/FLANGE';
UPDATE product_catalog SET cost_price = 277.51 WHERE name = 'QUADRO COMANDO 400X400X200 COM FLANGE';
UPDATE product_catalog SET cost_price = 186.78 WHERE name = 'QUADRO COMANDO 500X400X200 COM FLANGE';
UPDATE product_catalog SET cost_price = 83.49 WHERE name = 'REGISTRO ESFERA METAL 1.1/2"';
UPDATE product_catalog SET cost_price = 38.23 WHERE name = 'Registro esfera latão alavanca 1"';
UPDATE product_catalog SET cost_price = 168.5 WHERE name = 'Registro esfera metal 2"';
UPDATE product_catalog SET cost_price = 153.26 WHERE name = 'Registro bruto de gaveta 2" polegada';
UPDATE product_catalog SET cost_price = 15.55 WHERE name = 'Registro 3/4" esfera';
UPDATE product_catalog SET cost_price = 685.81 WHERE name = 'Registro bruto gaveta 4" polegada';
UPDATE product_catalog SET cost_price = 178.64 WHERE name = 'REGISTRO ESFERA METAL 2" POLEGADA';
UPDATE product_catalog SET cost_price = 10.72 WHERE name = 'SELANTE PU BRANCO 400GR PU40';
UPDATE product_catalog SET cost_price = 66.95 WHERE name = 'SIRENE SINALIZADOR AUDIOVISUAL CONVENCIONAL. COM SIRENE';
UPDATE product_catalog SET cost_price = 95.93 WHERE name = 'SINALIZADOR DUPLO COM FOTOCELULA';
UPDATE product_catalog SET cost_price = 215.58 WHERE name = 'SINALIZADOR AUDIOVISUAL ENDER. SMART';
UPDATE product_catalog SET cost_price = 13.35 WHERE name = 'Te galvanizado  1" POLEGADA 90GR';
UPDATE product_catalog SET cost_price = 42.36 WHERE name = 'Te galvanizado 2" POLEGADA 90GR';
UPDATE product_catalog SET cost_price = 8.43 WHERE name = 'Te galvanizado  3/4" 90GR';
UPDATE product_catalog SET cost_price = 110 WHERE name = 'Te galvanizado 3"POLEGADA 90GR';
UPDATE product_catalog SET cost_price = 109.86 WHERE name = 'Te galvanizado 4" 90GR';
UPDATE product_catalog SET cost_price = 31.48 WHERE name = 'Te reduzido galvanizado 1.1/2 x 1"';
UPDATE product_catalog SET cost_price = 16.11 WHERE name = 'Te reduzido 1"x1/2 galvanizado';
UPDATE product_catalog SET cost_price = 98.38 WHERE name = 'Tee reduzido 2 1/2" x 1"';
UPDATE product_catalog SET cost_price = 45.99 WHERE name = 'Te reduzido 2"x 1"galvanizado';
UPDATE product_catalog SET cost_price = 222.51 WHERE name = 'Tubo  galvanizado 1.1/4" galvanizado 6M';
UPDATE product_catalog SET cost_price = 195.9 WHERE name = 'Tubo galvanizado 1" galvanizado';
UPDATE product_catalog SET cost_price = 429.25 WHERE name = 'Tubo galvanizado 2.1/2" 6Metro';
UPDATE product_catalog SET cost_price = 428.95 WHERE name = 'Tubo galvanizado 2" galvanizado 6M';
UPDATE product_catalog SET cost_price = 132.57 WHERE name = 'Tubo 3/4" galvanizado';
UPDATE product_catalog SET cost_price = 569.65 WHERE name = 'Tubo 3" galvanizado';
UPDATE product_catalog SET cost_price = 943.41 WHERE name = 'Tubo galvanizado 4" Polegadas  6M';
UPDATE product_catalog SET cost_price = 15 WHERE name = 'Tubo, ELETROD GALV ZINC 3M LEV 3/4"';
UPDATE product_catalog SET cost_price = 309.63 WHERE name = 'Tubo galvanizado 1 1/2" galvanizado.';
UPDATE product_catalog SET cost_price = 36.3 WHERE name = 'UNIA DE 1" GALVANIZADO COM ASSENTO BRONZE';
UPDATE product_catalog SET cost_price = 166.95 WHERE name = 'União galvanizado 2 1/2" assento bronze';
UPDATE product_catalog SET cost_price = 99.58 WHERE name = 'União galvanizado assento bronze 2"';
UPDATE product_catalog SET cost_price = 31.35 WHERE name = 'União Galvanizado com assento bronze  3/4"';
UPDATE product_catalog SET cost_price = 506.92 WHERE name = 'União Galvanizado Assento Bronze 4"';
UPDATE product_catalog SET cost_price = 24.22 WHERE name = 'União soldável de PVC 50 mm';
UPDATE product_catalog SET cost_price = 1.83 WHERE name = 'Unidut  multiplo Conector caixa  condulete 3/4';
UPDATE product_catalog SET cost_price = 1.78 WHERE name = 'Conector para caixa multipla petrolet 3/4';
UPDATE product_catalog SET cost_price = 48.52 WHERE name = 'Válvula Retençao Horizontal 1"';
UPDATE product_catalog SET cost_price = 57.54 WHERE name = 'Válvula De Retençao Vertical 1 1/4"';
UPDATE product_catalog SET cost_price = 302.71 WHERE name = 'Válvula De Retençao Horizontal 2 1/2"';
UPDATE product_catalog SET cost_price = 139.13 WHERE name = 'Válvula De Retençao Vertical 2"';
UPDATE product_catalog SET cost_price = 321.54 WHERE name = 'Válvula De Retençao Vertical 3"';
UPDATE product_catalog SET cost_price = 242.74 WHERE name = 'Válvula de retenção vertical 2.1/2"';
UPDATE product_catalog SET cost_price = 159.85 WHERE name = 'Válvula De Retençao horizontal de 2"';
UPDATE product_catalog SET cost_price = 745.17 WHERE name = 'VálvulaDe Retençao horizontal de 4"';
UPDATE product_catalog SET cost_price = 11.47 WHERE name = 'TE GALVANIZADO DE REDUCAO 3/4X1/2"';
UPDATE product_catalog SET cost_price = 3.85 WHERE name = 'NIPLE DUPLO GALVANIZADO 1/2"';
UPDATE product_catalog SET cost_price = 52.84 WHERE name = 'TAMPAO CEGO COM /CORRENTE 2.1/2" ALUM';
UPDATE product_catalog SET cost_price = 10.78 WHERE name = 'REGISTRO ESFERA METAL 1/2"';
UPDATE product_catalog SET cost_price = 5.19 WHERE name = 'CONECTOR PRA /HASTE DE ATERRAMENTO 5/8 GTDU';
UPDATE product_catalog SET cost_price = 28.94 WHERE name = 'CORDOALHA 35MM COBRE NU';
UPDATE product_catalog SET cost_price = 61 WHERE name = 'Compound adesivo epoxi, vedacit. 1kg,';
UPDATE product_catalog SET cost_price = 48.83 WHERE name = 'CABO PP 4X10MM 1KV CLASSE 2';
UPDATE product_catalog SET cost_price = 57.04 WHERE name = 'DISJUNTOR N TRIPOLAR.C 025A 3,0KA 5SL132-7MB';
UPDATE product_catalog SET cost_price = 248 WHERE name = 'ACIONADOR MANUAL ENDERECAVEL - IRIS MCP150';
UPDATE product_catalog SET cost_price = 44.31 WHERE name = 'Detector de fumaça Convencional 12v/24v';
UPDATE product_catalog SET cost_price = 1000 WHERE name = 'Descida de Spda aparente em metro';
UPDATE product_catalog SET cost_price = 2.07 WHERE name = 'CURVA CONDULETE SOLD PVC  90 3/4"';
UPDATE product_catalog SET cost_price = 97.58 WHERE name = 'Tubo 1/2" galvanizado 6m';
UPDATE product_catalog SET cost_price = 70.33 WHERE name = 'Cotovelo 2 1/2" polegadas galvanizado 45º';
UPDATE product_catalog SET cost_price = 8.37 WHERE name = 'TRINCHA 4" CERDA TRADICIONAL 302';
UPDATE product_catalog SET cost_price = 4.59 WHERE name = 'Cotovelo 1/2" polegadas galvanizado 90º';
UPDATE product_catalog SET cost_price = 84.68 WHERE name = 'Luva  galvanizado 3''''';
UPDATE product_catalog SET cost_price = 22.01 WHERE name = 'Cotovelo 1 1/2" galvanizado 45º';
UPDATE product_catalog SET cost_price = 4.61 WHERE name = 'Cotovelo 1/2" galvanizado 45º';
UPDATE product_catalog SET cost_price = 137.44 WHERE name = 'Bloco autônomo led de emergência 2200 Lumens 2 farois';
UPDATE product_catalog SET cost_price = 120 WHERE name = 'Bateria 12v 2.3 ah';
UPDATE product_catalog SET cost_price = 8.41 WHERE name = 'Tirante ( Barra roscada zincada de 1/4 3m")';
UPDATE product_catalog SET cost_price = 80 WHERE name = 'Fechadura Para Porta Corta Fogo Sobrepor S/chave Cor Preto';
UPDATE product_catalog SET cost_price = 86.63 WHERE name = 'FITA ANTI DERRAPAANTE 50MMX20MT PRETO';
UPDATE product_catalog SET cost_price = 1.85 WHERE name = 'ABRACADEIRA GOTA 2.1/2"';
UPDATE product_catalog SET cost_price = 303 WHERE name = 'DR Disjuntor diferencial 4 Polos 100A 30ma WEG';
UPDATE product_catalog SET cost_price = 300 WHERE name = 'Detector fumaça op720 Siemens';
UPDATE product_catalog SET cost_price = 255 WHERE name = 'Detector de Temperatura HI722 Siemens da 722pro';
UPDATE product_catalog SET cost_price = 35 WHERE name = 'PARAFUSO PHILLIPS S8 4,8X45MM';
UPDATE product_catalog SET cost_price = 0.64 WHERE name = 'ADAPTADOR PVC 01/2" Vermelho';
UPDATE product_catalog SET cost_price = 3.25 WHERE name = 'CURVA GALV ZINC 90 3/4"';
UPDATE product_catalog SET cost_price = 467 WHERE name = 'MÓDULO DE ZONA TELETEK MCZ';
UPDATE product_catalog SET cost_price = 206 WHERE name = 'Mangueira de incêndio tipo 1';
UPDATE product_catalog SET cost_price = 253.57 WHERE name = 'ABRIGO, CAIXA DE INCENDIO EMBUTIR 90X60X17';
UPDATE product_catalog SET cost_price = 0.64 WHERE name = 'INP ADAPTADOR D PVC VERMELHO 01/2" ADP012V.';
UPDATE product_catalog SET cost_price = 1.79 WHERE name = 'Adaptador pra caixinha condulete vermelho 01/2';
UPDATE product_catalog SET cost_price = 1.74 WHERE name = 'Curva condulete vermelha 01/2 S/R';
UPDATE product_catalog SET cost_price = 1.37 WHERE name = 'Luva condulete pvc vermelha 01/2 S/R';
UPDATE product_catalog SET cost_price = 1.9 WHERE name = 'Abraçadeira pra condulete pvc vermelho 01/2';
UPDATE product_catalog SET cost_price = 2.91 WHERE name = 'Tampa cega pra condulete  vermelho 3/4';
UPDATE product_catalog SET cost_price = 4.55 WHERE name = 'Cabo de incêndio vermelho 2×1,5mm';
UPDATE product_catalog SET cost_price = 3.39 WHERE name = 'Tomada 2P+T PB 10A/250 S/Placa-20140/0';
UPDATE product_catalog SET cost_price = 2.28 WHERE name = 'Tampa condulete hexagonal vertical';
UPDATE product_catalog SET cost_price = 5.65 WHERE name = 'Caixa múltipla sem tampa Petrolete 03/4"';
UPDATE product_catalog SET cost_price = 6.94 WHERE name = 'Cordoalha de cobre nu 016mm';
UPDATE product_catalog SET cost_price = 3.36 WHERE name = 'Terminal botinha mc 016mm';
UPDATE product_catalog SET cost_price = 8.92 WHERE name = 'Conector Split Bolt CP 35mm';
UPDATE product_catalog SET cost_price = 305.09 WHERE name = 'Válvula de retenção Horizontal 3" polegadas';
UPDATE product_catalog SET cost_price = 144.59 WHERE name = 'Botina Nobuck Pu Biden Cafe';
UPDATE product_catalog SET cost_price = 28.91 WHERE name = 'Alicate universal 8" 1000v aço carbono';
UPDATE product_catalog SET cost_price = 11.81 WHERE name = 'Tinta spray vermelho 400ML 250gr';
UPDATE product_catalog SET cost_price = 2.61 WHERE name = 'Lâmpada led bulb 9w bv 810lm 3k';
UPDATE product_catalog SET cost_price = 2.42 WHERE name = 'Plafon pvc E27 100w';
UPDATE product_catalog SET cost_price = 2.89 WHERE name = 'Chave phillips 3/16×5" imantada';
UPDATE product_catalog SET cost_price = 3.78 WHERE name = 'Chave phillips 1/4×4" imantada';
UPDATE product_catalog SET cost_price = 1.66 WHERE name = 'Chave phillips 1/8×6" imantada';
UPDATE product_catalog SET cost_price = 1.52 WHERE name = 'CHAVE DE FENDA 1/8X5" IMANTADA';
UPDATE product_catalog SET cost_price = 1.79 WHERE name = 'CHAVE PHILLIPS 1/8X6" IMANTADA';
UPDATE product_catalog SET cost_price = 1.48 WHERE name = 'CHAVE PHILLIPS 1/8X2" IMANTADA';
UPDATE product_catalog SET cost_price = 16.64 WHERE name = 'FILTRO DE LINHA 3 TOMADA 2P+T PT';
UPDATE product_catalog SET cost_price = 13.13 WHERE name = 'SERRA COPO AÇO RAP BI-METAL 22MM 7/8"';
UPDATE product_catalog SET cost_price = 79.69 WHERE name = 'CAIXA MEDIDOR TRIFÁSICO P1 VISOR DE VIDRO - 52X26X18CM';
UPDATE product_catalog SET cost_price = 210.04 WHERE name = 'VALVULA DE RETENÇÃO HORIZONTAL 2.1/2';
UPDATE product_catalog SET cost_price = 110.12 WHERE name = 'UNIAO GALVANIZADO 2.1/2 ASS.BRONZE';
UPDATE product_catalog SET cost_price = 11.62 WHERE name = 'TE GALVANIZADO RED 1X1/2';
UPDATE product_catalog SET cost_price = 7.55 WHERE name = 'Niple galvanizado 1.1/4"';
UPDATE product_catalog SET cost_price = 7.94 WHERE name = 'Tubo pvc vermelho 01/2"';
UPDATE product_catalog SET cost_price = 0.64 WHERE name = 'Adaptador pra caixa de pvc vermelho /2"';
UPDATE product_catalog SET cost_price = 0.49 WHERE name = 'Braçadeira vermelho de pvc  01/2"';
UPDATE product_catalog SET cost_price = 3.14 WHERE name = 'Caixa entradas pra pvc vermelho 03/4"';
UPDATE product_catalog SET cost_price = 3.25 WHERE name = 'Cotovelo de pvc vermelho 01/2"';
UPDATE product_catalog SET cost_price = 1.76 WHERE name = 'Curva de pvc vermelho 90°graus 01/2"';
UPDATE product_catalog SET cost_price = 0.25 WHERE name = 'Tampão pra caixa de pvc vermelho';
UPDATE product_catalog SET cost_price = 3.14 WHERE name = 'Caixa entrada de pvc cinza 03/4"';
UPDATE product_catalog SET cost_price = 0.58 WHERE name = 'Adaptador de pvc cinza 01/2"';
UPDATE product_catalog SET cost_price = 2.37 WHERE name = 'Cotovelo pvc cinza 01/2"';
UPDATE product_catalog SET cost_price = 0.45 WHERE name = 'Braçadeira pvc cinza 01/2"';
UPDATE product_catalog SET cost_price = 1.36 WHERE name = 'Tampa condulete cega cinza pvc 03/4"';
UPDATE product_catalog SET cost_price = 7.88 WHERE name = 'Tubo eletroduto condulete pvc vermelho 01/2"';
UPDATE product_catalog SET cost_price = 1.78 WHERE name = 'Conector pra caixa múltipla 03/4"';
UPDATE product_catalog SET cost_price = 9.56 WHERE name = 'Te galvanizado 1"';
UPDATE product_catalog SET cost_price = 2.76 WHERE name = 'Bucha de redução galvanizado 1/2"×1/4"';
UPDATE product_catalog SET cost_price = 4.95 WHERE name = 'Cabo de incêndio Blindado vermelho 2x1,5mm 600v';
UPDATE product_catalog SET cost_price = 322.87 WHERE name = 'Módulo zona DI-9319E GST';
UPDATE product_catalog SET cost_price = 192.88 WHERE name = 'Detector optico de fumaça endereçavel DI-9102E GST';
UPDATE product_catalog SET cost_price = 115 WHERE name = 'Detector de fumaça endereçavel-3 fios se D-13120199m base';
UPDATE product_catalog SET cost_price = 115 WHERE name = 'Detector de temperatura Térmico E Termovelocimétrico - 3 Fios SEM BASE.D13120243';
UPDATE product_catalog SET cost_price = 1825 WHERE name = 'CENTRAL ALARME ENDEREÇAVEL SIRIUS COMPACT II 125 1L S/BAT';
UPDATE product_catalog SET cost_price = 86 WHERE name = 'BATERIA ESTACIONÁRIA SELADA 12V2,2A';
UPDATE product_catalog SET cost_price = 92 WHERE name = 'ACIONADOR MANUAL SOBREPOR SIRIUS AMQ-D';
UPDATE product_catalog SET cost_price = 135 WHERE name = 'SIRENE AUDIOVISUAL SOBREPOR SIRIUS SAVQI-D';
UPDATE product_catalog SET cost_price = 120 WHERE name = 'DETECTOR DE FUMACA OPTICO BRANCO SIRIUS SDO-D';
UPDATE product_catalog SET cost_price = 125 WHERE name = 'DETECTOR DE TEMPERATURA TERMOVELOCIMETRICO BRANCO SIRIUS TDV-D A2';
UPDATE product_catalog SET cost_price = 1080 WHERE name = 'PROGRAMADOR PORTATIL ENDERECAVEL PPD-E';
UPDATE product_catalog SET cost_price = 205 WHERE name = 'MODULO DE ENTRADA DE ZONA SIRIUS MZE2-D';
UPDATE product_catalog SET cost_price = 76 WHERE name = 'DETECTOR FUMACA OPTICO  CONVENCIONAL SDO-C';
UPDATE product_catalog SET cost_price = 269 WHERE name = 'CENTRAL ALARME CONVENCIONAL CAC 06.24 S/BAT';
UPDATE product_catalog SET cost_price = 260 WHERE name = 'DETECTOR ENDEREÇÁVEL DE FUMAÇA IRIS S130 COM BASE';
UPDATE product_catalog SET cost_price = 45 WHERE name = 'ACOPLAMENTO RANHURADO RIGIDO 3"';
UPDATE product_catalog SET cost_price = 9.73 WHERE name = 'Broca Plus sds 08×110mm';
UPDATE product_catalog SET cost_price = 4.71 WHERE name = 'Niple duplo redução galvanizado 1/2"×1/4"';
UPDATE product_catalog SET cost_price = 2.74 WHERE name = 'Luva pra mão pu tátil forr PT M';
UPDATE product_catalog SET cost_price = 2.76 WHERE name = 'Bucha de redução galvanizado 1/2"×1/4"';
UPDATE product_catalog SET cost_price = 14.83 WHERE name = 'Te galvanizado de redução 1×1/2"';
UPDATE product_catalog SET cost_price = 4.65 WHERE name = 'Broca Plus sds 06×160mm';
UPDATE product_catalog SET cost_price = 5.92 WHERE name = 'Broca Plus sds 10×160mm';
UPDATE product_catalog SET cost_price = 2.62 WHERE name = 'Luva pra mão pu tátil forr smart PT G';
UPDATE product_catalog SET cost_price = 2.62 WHERE name = 'Luva pra mão pu tátil forr smart PT P';
UPDATE product_catalog SET cost_price = 16.98 WHERE name = 'Te ranhurado mecanico sprink 2×3/4"';
UPDATE product_catalog SET cost_price = 2.83 WHERE name = 'Óculos leopardo incolor';
UPDATE product_catalog SET cost_price = 24.18 WHERE name = 'Registro esfera metal alavancar 1"';
UPDATE product_catalog SET cost_price = 5.5 WHERE name = 'Niple duplo galvanizado 1/4"';
UPDATE product_catalog SET cost_price = 39.87 WHERE name = 'Denverpoxi 1kg';
UPDATE product_catalog SET cost_price = 6.38 WHERE name = 'Disjuntor monofásico 25A 3KA -curva B';
UPDATE product_catalog SET cost_price = 574.3 WHERE name = 'Válvula de retenção Horizontal 3" docol';
UPDATE product_catalog SET cost_price = 0.71 WHERE name = 'Clips conector U pra cabo de aço (D) 5/16-8,0mm';
UPDATE product_catalog SET cost_price = 242.74 WHERE name = 'Válvula de retenção vertical 2.1/2"';
UPDATE product_catalog SET cost_price = 214.47 WHERE name = 'Adesivo epoxi profissional 1.8kg (araldite) brascola';
UPDATE product_catalog SET cost_price = 23.51 WHERE name = 'Niple galvanizado de 2.1/2" polegadas';
UPDATE product_catalog SET cost_price = 58.71 WHERE name = 'Cotovelo galvanizado de 90º 3" podegadas segurimax';
UPDATE product_catalog SET cost_price = 78.33 WHERE name = 'Te galvanizado 3"polegadas';
UPDATE product_catalog SET cost_price = 28.22 WHERE name = 'Bucha de redução galvanizado 3×2.1/2"';
UPDATE product_catalog SET cost_price = 116.42 WHERE name = 'União galvanizado 3" polegadas ass.plano';
UPDATE product_catalog SET cost_price = 195.84 WHERE name = 'Registro gaveta bruto 2.1/2" polegadas';
UPDATE product_catalog SET cost_price = 263.57 WHERE name = 'Abrigo, caixa para Mangueira 90x60x17 Embutir';
UPDATE product_catalog SET cost_price = 44.39 WHERE name = 'ACIONADOR MANUAL CONVENCIONAL COM SIRENE , SEGURIMAX';
UPDATE product_catalog SET cost_price = 40.54 WHERE name = 'BASE MASTRO 1.1/2" POLEGADAS,ACO ELET';
UPDATE product_catalog SET cost_price = 335.54 WHERE name = 'CABO FLEXIVEL 4,0MM VERMELHO 750V';
UPDATE product_catalog SET cost_price = 283.06 WHERE name = 'TAMPAO FERRO 60X60 SIMPLES';
UPDATE product_catalog SET cost_price = 59.51 WHERE name = 'TAMPAO FERRO T-16 LISO 30X30';
UPDATE product_catalog SET cost_price = 43.96 WHERE name = 'TAMPAO FERRO T-16 TEL 25X25';
UPDATE product_catalog SET cost_price = 4.67 WHERE name = 'CANALETA 20X10X2000MM BR S/DIV COM FITA';
UPDATE product_catalog SET cost_price = 36.39 WHERE name = 'TAMPAO CEGO COM/CORRENTE 1.1/2" ALUM';
UPDATE product_catalog SET cost_price = 106.03 WHERE name = 'CONTATOR 3TS31 12A 220V 1NA';
UPDATE product_catalog SET cost_price = 24.06 WHERE name = 'CORDOALHA 50MM COBREADA NORMATIZADA';
UPDATE product_catalog SET cost_price = 13.5 WHERE name = 'CORDOALHA 16MM COBRE NU';
UPDATE product_catalog SET cost_price = 8.22 WHERE name = 'CORDOALHA 16MM COBREADA NORMATIZADA';
UPDATE product_catalog SET cost_price = 10.37 WHERE name = 'COTOVELO GALVANIZADO 1" 90';
UPDATE product_catalog SET cost_price = 53.83 WHERE name = 'COTOVELO GALVANIZADO 2.1/2" 90';
UPDATE product_catalog SET cost_price = 95.91 WHERE name = 'COTOVELO GALVANIZADO 45, 3" POLEGADA';
UPDATE product_catalog SET cost_price = 7.42 WHERE name = 'COTOVELO GALVANIZADO 45 3/4"';
UPDATE product_catalog SET cost_price = 160.91 WHERE name = 'COTOVELO GALVANIZADO 4" ,90';
UPDATE product_catalog SET cost_price = 15.27 WHERE name = 'COTOVELO GALVANIZADO,1.1/4" ,90';
UPDATE product_catalog SET cost_price = 22.01 WHERE name = 'COTOVELO GALVANIZADO 1.1/2" ,45';
UPDATE product_catalog SET cost_price = 3.25 WHERE name = 'CURVA GALV ZINCADO 90, 3/4"';
UPDATE product_catalog SET cost_price = 83.69 WHERE name = 'ESGUICHO 1.1/2" JATO REGUL 3 POS ALUM';
UPDATE product_catalog SET cost_price = 111.47 WHERE name = 'CAPTOR FRANKLIN COM,1 DECIDA 300MM LATAO 3/4';
UPDATE product_catalog SET cost_price = 1183.74 WHERE name = 'CENTRAL DE INCENDIO 80 LACOS 24V COMPACT SUGURIMAX';
UPDATE product_catalog SET cost_price = 659.39 WHERE name = 'CENTRAL INCENDIO 24 LACOS 24V CONVENCIONAL SEGURIMAX';
UPDATE product_catalog SET cost_price = 15.66 WHERE name = 'CHAVE DUPL PRA CONEXOES 1.1/2X2.1/2" LATAO';
UPDATE product_catalog SET cost_price = 26.43 WHERE name = 'ADAPTADOR PRA ESGUICHO 2.1/2X2.1/2" ALUMINIO';
UPDATE product_catalog SET cost_price = 47.03 WHERE name = 'ESTICADOR PRA CABO DE ACO 3/4-20MM';
UPDATE product_catalog SET cost_price = 2.95 WHERE name = 'ESTICADOR PRA CABO DE ACO 3/16-5MM';
UPDATE product_catalog SET cost_price = 16.42 WHERE name = 'ESTICADOR PRA CABO DE ACO 5/8-16MM';
UPDATE product_catalog SET cost_price = 3.79 WHERE name = 'ESTICADOR PRA CABO DE ACO 5/16-08MM';
UPDATE product_catalog SET cost_price = 9.81 WHERE name = 'ESTICADOR PRA CABO DE ACO 1/2-12MM';
UPDATE product_catalog SET cost_price = 25.01 WHERE name = 'FITA ANTI DERRAPANTE 50MMX05MT PRETO';
UPDATE product_catalog SET cost_price = 103.39 WHERE name = 'CABO PP 4X25MM 1KV HEPR MT';
UPDATE product_catalog SET cost_price = 22.49 WHERE name = 'CABO PP 4X25MM 1KV HEPR METRO';
UPDATE product_catalog SET cost_price = 6.88 WHERE name = 'CABO PP 4X 1,5MM 500V';
UPDATE product_catalog SET cost_price = 7.88 WHERE name = 'CABO PP 3X 2,5MM 1KV HEPR MT';
UPDATE product_catalog SET cost_price = 19.39 WHERE name = 'CABO PP 3X 6,0MM 1KV HEPR MT';
UPDATE product_catalog SET cost_price = 2.34 WHERE name = 'FITA ISOLANTE 18MMX10MT CZ';
UPDATE product_catalog SET cost_price = 17.99 WHERE name = 'FITA ISOLANTE AUTOFUSAO 05MT PT23';
UPDATE product_catalog SET cost_price = 1.97 WHERE name = 'FITA ISOLANTE 19MMX10METRO AZUL';
UPDATE product_catalog SET cost_price = 1.79 WHERE name = 'FITA ISOLANTE 19MMX10MT VERMELHO';
UPDATE product_catalog SET cost_price = 1.8 WHERE name = 'FITA ISOLANTE 19MMX10MT AMARELO';
UPDATE product_catalog SET cost_price = 29.79 WHERE name = 'FITA DUPLA FACE ACR 19MMX20MT FITA FORTE 080';
UPDATE product_catalog SET cost_price = 20.48 WHERE name = 'FITA DUPLA FACE ACR 12MMX20MT FITA FORTE';
UPDATE product_catalog SET cost_price = 8.79 WHERE name = 'FITA ZEBRADA 70MMX200M PT/AM';
UPDATE product_catalog SET cost_price = 24.64 WHERE name = 'FITA DEMARCACAO SOLO 50MMX30MT VERMELHO';
UPDATE product_catalog SET cost_price = 1.72 WHERE name = 'FITA VEDA ROSCA 18MMX25 METRO';
UPDATE product_catalog SET cost_price = 33.16 WHERE name = 'ADAPTADOR AA FLANGE+ANEL CAIXA DAGUA 60MM 2"';
UPDATE product_catalog SET cost_price = 55.67 WHERE name = 'AGUA RAZ 5LT';
UPDATE product_catalog SET cost_price = 0.61 WHERE name = 'ABRAÇADEIRA TIPO D COM CUNHA 3/4"';
UPDATE product_catalog SET cost_price = 10 WHERE name = 'TINTA SPRAY U.G VERMELHO 250ML 120GR';
UPDATE product_catalog SET cost_price = 9.1 WHERE name = 'TINTA SPRAY U.G BRANCO FO 250ML 120GR';
UPDATE product_catalog SET cost_price = 9.23 WHERE name = 'TINTA SPRAY U.G GRAFITE 250ML 120GR';
UPDATE product_catalog SET cost_price = 10.38 WHERE name = 'ISOLADOR REF CHAPA ENCOSTO ACO ELET';
UPDATE product_catalog SET cost_price = 13.71 WHERE name = 'ISOLADOR REF 1 DC MASTRO 1.1/2" ACO ELET';
UPDATE product_catalog SET cost_price = 18.45 WHERE name = 'ISOLADOR SIMP 2 DECIDA MASTRO 2" ACO ELET';
UPDATE product_catalog SET cost_price = 36.13 WHERE name = 'HASTE P/ATERRAMENTO 5/8" 3,00M';
UPDATE product_catalog SET cost_price = 4.82 WHERE name = 'JOELHO PVC SOLDAVEL 45 50MM';
UPDATE product_catalog SET cost_price = 131.74 WHERE name = 'BLOCO DE EMERGENCIA LED 400 LUMENS';
UPDATE product_catalog SET cost_price = 126.18 WHERE name = 'BLOCO DE EMERGENCIA LED 300 LUMENS';
UPDATE product_catalog SET cost_price = 138.25 WHERE name = 'BLOCO DE EMERGENCIA LED 1200 LUMENS';
UPDATE product_catalog SET cost_price = 72.15 WHERE name = 'BLOCO DE EMERGENCIA LED 200 LUMENS';
UPDATE product_catalog SET cost_price = 465.81 WHERE name = 'BLOCO DE EMERGENCIA LED 3000 LUMENS';
UPDATE product_catalog SET cost_price = 22.11 WHERE name = 'BUCHA FIXACAO PLAST S08 COM,1000 COM ANEL';
UPDATE product_catalog SET cost_price = 13.81 WHERE name = 'BUCHA FIXACAO PLAST S06 COM,1000 COM ANEL';
UPDATE product_catalog SET cost_price = 14.97 WHERE name = 'BUCHA FIXACAO PLAST S05 COM 1000 COM ANEL';
UPDATE product_catalog SET cost_price = 18.8 WHERE name = 'BUCHA FIXACAO PLAST S08 COM 1000 SEM ANEL';
UPDATE product_catalog SET cost_price = 21.41 WHERE name = 'BUCHA FIXACAO PLAST S10 COM/500 CCOM/ANEL';
UPDATE product_catalog SET cost_price = 11.16 WHERE name = 'MAO FRANCESA 30CM PRATA';
UPDATE product_catalog SET cost_price = 236.82 WHERE name = 'MASTRO SIMPLES 3M 2" ACO GALV';
UPDATE product_catalog SET cost_price = 7.67 WHERE name = 'NIPLE DUPLO GALV 1"';
UPDATE product_catalog SET cost_price = 34.46 WHERE name = 'NIPLE DUPLO GALV 2.1/2"';
UPDATE product_catalog SET cost_price = 22.05 WHERE name = 'NIPLE DUPLO GALV 2"';
UPDATE product_catalog SET cost_price = 2.81 WHERE name = 'CHUMBADOR CBA 3/8X3.1/2" COM PARAFUSO';
UPDATE product_catalog SET cost_price = 414.19 WHERE name = 'CAIXA PROTECAO GERAL CEB';
UPDATE product_catalog SET cost_price = 78.31 WHERE name = 'BUCHA DE RED GALVANIZADO 4X2.1/2"';
UPDATE product_catalog SET cost_price = 50.16 WHERE name = 'COTOVELO RANHURADO 45 2.1/2" 76MM';
UPDATE product_catalog SET cost_price = 45.98 WHERE name = 'COTOVELO RANHURADO 90 2.1/2" 73MM';
UPDATE product_catalog SET cost_price = 71.92 WHERE name = 'TE RANHURADO 2.1/2" 73MM';
UPDATE product_catalog SET cost_price = 34 WHERE name = 'ACOPLAMENTO RANHURADO RIGIDO 2.1/2" 73MM';
UPDATE product_catalog SET cost_price = 76.18 WHERE name = 'TE RANHURADO MECANICO 4X2.1/2" 73MM';
UPDATE product_catalog SET cost_price = 81.29 WHERE name = 'TIMER DIGITAL P/TRILHO DIN 35MM';
UPDATE product_catalog SET cost_price = 10.23 WHERE name = 'SELANTE PU PRETO 400GR PU40';
UPDATE product_catalog SET cost_price = 20.33 WHERE name = 'TE GALVANIZADO 90 1.1/4"';
UPDATE product_catalog SET cost_price = 4.54 WHERE name = 'BOTINHA TERMINAL DE PRESSAO 16MM';
UPDATE product_catalog SET cost_price = 97.58 WHERE name = 'TUBO GALV C/COST BS LEV 6M 5580 1/2"';
UPDATE product_catalog SET cost_price = 471.36 WHERE name = 'TUBO GALVANIZADO C/COST BS LEV 6M 5580 2.1/2"';
UPDATE product_catalog SET cost_price = 2.81 WHERE name = 'UNIDUT RETO CONECTOR LUVA 3/4"';
UPDATE product_catalog SET cost_price = 5 WHERE name = 'Placas de Sinalização';
UPDATE product_catalog SET cost_price = 36.86 WHERE name = 'TAMPAO GALVANIZADO C/SEXTAVADO 2.1/2"';
UPDATE product_catalog SET cost_price = 6.26 WHERE name = 'TAMPAO GALV C/SEXTAVADO 1"';
UPDATE product_catalog SET cost_price = 17.77 WHERE name = 'TAMPAO GALV C/SEXTAVADO 2"';
UPDATE product_catalog SET cost_price = 4.41 WHERE name = 'TAMPAO GALV C/SEXTAVADO 3/4"';
UPDATE product_catalog SET cost_price = 348.28 WHERE name = 'TE GALVANIZADO 45 3"';
UPDATE product_catalog SET cost_price = 23.63 WHERE name = 'TE RANHURADO 1"';
UPDATE product_catalog SET cost_price = 87.49 WHERE name = 'TE RANHURADO 3"';
UPDATE product_catalog SET cost_price = 51.85 WHERE name = 'TE RANHURADO 2"';
UPDATE product_catalog SET cost_price = 94.28 WHERE name = 'TE RANHURADO MECANICO 4X3"';
UPDATE product_catalog SET cost_price = 34.23 WHERE name = 'TE RANHURADO 1.1/4"';
UPDATE product_catalog SET cost_price = 34.61 WHERE name = 'TE RANHURADO MECANICO 2X1.1/2"';
UPDATE product_catalog SET cost_price = 20.14 WHERE name = 'TE RANHURADO MECANICO SPRINK 2X1" NPT';
UPDATE product_catalog SET cost_price = 23.87 WHERE name = 'TE RANHURADO MECANICO SPRINK 2.1/2X1" NPT';
UPDATE product_catalog SET cost_price = 17.87 WHERE name = 'TAMPAO RANHURADO 3"';
UPDATE product_catalog SET cost_price = 14.7 WHERE name = 'TAMPAO RANHURADO 2.1/2"';
UPDATE product_catalog SET cost_price = 27.48 WHERE name = 'ACOPLAMENTO RANHURADO RIGIDO 2" 1/36';
UPDATE product_catalog SET cost_price = 34.53 WHERE name = 'ACOPLAMENTO RANHURADO RIGIDO 2.1/2" 76MM';
UPDATE product_catalog SET cost_price = 45 WHERE name = 'ACOPLAMENTO RANHURADO RIGIDO 3"';
UPDATE product_catalog SET cost_price = 57.24 WHERE name = 'COTOVELO RANHURADO 90 3"';
UPDATE product_catalog SET cost_price = 32.55 WHERE name = 'COTOVELO RANHURADO 90 2"';
UPDATE product_catalog SET cost_price = 45.52 WHERE name = 'COTOVELO RANHURADO 45 2.1/2" 73MM';
UPDATE product_catalog SET cost_price = 94.28 WHERE name = 'TE RANHURADO MECANICO  4X3"';
UPDATE product_catalog SET cost_price = 42.3 WHERE name = 'TE RANHURADO MECANICO  2X1.1/4" 60X42MM';
UPDATE product_catalog SET cost_price = 42.3 WHERE name = 'TE RANHURADO MEC 2X1.1/4" 60X42MM';
UPDATE product_catalog SET cost_price = 12.8 WHERE name = 'BUJAO GALVANIZADO 2''''';
UPDATE product_catalog SET cost_price = 36.27 WHERE name = 'BUJAO GALVANIZADO 3''''';
UPDATE product_catalog SET cost_price = 0.59 WHERE name = 'ABRAÇADEIRA TIPO GOTA 3/4';
UPDATE product_catalog SET cost_price = 1.9 WHERE name = 'ABRAÇADEIRA TIPO COPO 3/4';
UPDATE product_catalog SET cost_price = 29.32 WHERE name = 'BUCHA DE REDUÇAO 2.1/2X2''''';
UPDATE product_catalog SET cost_price = 40.92 WHERE name = 'BUCHA DE REDUÇAO 3X2.1/2''''';
UPDATE product_catalog SET cost_price = 100 WHERE name = 'MANOMETRO DN63 S VERT CAIXA INOX C-GLIC BSP 1-4 0A 10BAR';
UPDATE product_catalog SET cost_price = 20 WHERE name = 'Lampada de emergência';
UPDATE product_catalog SET cost_price = 1000 WHERE name = 'Infra Hidrante Galvanizado em metro';
UPDATE product_catalog SET cost_price = 1000 WHERE name = 'Infra alarme zincado em metro';
UPDATE product_catalog SET cost_price = 1000 WHERE name = 'Infra Sprinkler Galvanizado em metro';
UPDATE product_catalog SET cost_price = 1000 WHERE name = 'Infra Luminária, Lampada em metro';
UPDATE product_catalog SET cost_price = 9.65 WHERE name = 'silicone acético preto 250ml';
UPDATE product_catalog SET cost_price = 3.36 WHERE name = 'ADAPTADOR PRENSA CABO 1/2''''';
UPDATE product_catalog SET cost_price = 8.85 WHERE name = 'LUK SINALEIRO LED VD AD16 22A 220V';
UPDATE product_catalog SET cost_price = 16.82 WHERE name = 'Botão comutador 2 estágio luk, quadro de comando.';
UPDATE product_catalog SET cost_price = 11.98 WHERE name = 'ESPUMA EXPANSIVA PU 500ML';
UPDATE product_catalog SET cost_price = 46.46 WHERE name = 'NIPLE GALVANIZADO 3''''';
UPDATE product_catalog SET cost_price = 81.82 WHERE name = 'COTOVELO GALVANIZADO 3''''';
UPDATE product_catalog SET cost_price = 374.04 WHERE name = 'REGISTRO BRUTO DE GAVETA 3''''';
UPDATE product_catalog SET cost_price = 32.81 WHERE name = 'REGISTRO BRUTO DE GAVETA 3/4''''';
UPDATE product_catalog SET cost_price = 10.28 WHERE name = 'TOMADA EM BARRA 2PXT 10A PRETA';
UPDATE product_catalog SET cost_price = 11.69 WHERE name = 'TINTA SPRAY USO GERAL PRETO FOSCO 400ML';
UPDATE product_catalog SET cost_price = 11.29 WHERE name = 'TINTA SPRAY USO GERAL BRANCO FOSCO 400ML';
UPDATE product_catalog SET cost_price = 58.48 WHERE name = 'TE GALVANIZADO 2.1/2';
UPDATE product_catalog SET cost_price = 83.05 WHERE name = 'TE GALVANIZADO 2.1/2''''';
UPDATE product_catalog SET cost_price = 126.31 WHERE name = 'CONTATOR 3TS 33-11-220V 025A 0AN2';
UPDATE product_catalog SET cost_price = 10.72 WHERE name = 'DISJUNTOR N UNIPOLAR.C 010A 3,0KA 5SL1110-7MB';
UPDATE product_catalog SET cost_price = 82.65 WHERE name = 'TERMINAL PRE ISOLADO TP23-6 OLHAL AM 100';
UPDATE product_catalog SET cost_price = 2.55 WHERE name = 'CONECTOR SAK 0O4.00 WDU BG';
UPDATE product_catalog SET cost_price = 3.22 WHERE name = 'CNX POSTE PLASTICO WEW35/2';
UPDATE product_catalog SET cost_price = 12.5 WHERE name = 'Puxador para abrigo de hidrante em aço, redondo';
UPDATE product_catalog SET cost_price = 19 WHERE name = 'Acrílico com adesivo mensagem no visor ( incêndio) para abrigo de hidrante..';
UPDATE product_catalog SET cost_price = 79.57 WHERE name = 'Registro angular pra hidrante 45 2.1/2''''';
UPDATE product_catalog SET cost_price = 50 WHERE name = 'Mangueira corrugada de 1/2mm 50m';
UPDATE product_catalog SET cost_price = 100 WHERE name = 'Caixa de inpeção de aterramento com tampa em FF T16';
UPDATE product_catalog SET cost_price = 194 WHERE name = 'Caixa de Incêndio Abrigo sobrepor pequena 75x45x17';
UPDATE product_catalog SET cost_price = 96 WHERE name = 'Manômetro 0-300psi Glp';
UPDATE product_catalog SET cost_price = 300 WHERE name = 'Regulador segundo estágio com Manômetro';
UPDATE product_catalog SET cost_price = 400 WHERE name = 'Regulador de Primeiro Estágio Com Manômetro.';
UPDATE product_catalog SET cost_price = 100 WHERE name = 'Mangueira flexivel Glp Segundo Estágio.';
UPDATE product_catalog SET cost_price = 100 WHERE name = 'Mangueira primeiro Estágio Glp com Engate.';
UPDATE product_catalog SET cost_price = 5 WHERE name = 'Parabolt 1/4"';
UPDATE product_catalog SET cost_price = 10 WHERE name = 'Bucha de Redução galvanizado 3/4'' x 1/2"';
UPDATE product_catalog SET cost_price = 80 WHERE name = 'Registro gaveta 1.1/4"';
UPDATE product_catalog SET cost_price = 50 WHERE name = 'União 1.1/4"';